Benchmark = tsf

SRCDIR = ./src
SRCSUFFIX = c

CFLAGS = -g1 -DTSF_BUILD_SYSTEM=1
CINCLUDE = -I./src -I../../include

OPT = -O2
LDFLAGS = -lm

TEMPFILE = tsf_ir_speed_test_file.tsf

include ../../Makefile.in
