Benchmark = atax

SRCDIR = ./src
SRCSUFFIX = c

CFLAGS = -DPOLYBENCH_DUMP_ARRAYS -DPOLYBENCH_USE_C99_PROTO
CINCLUDE = -I${SRCDIR} -I../../../../include
OPT = -O2
LDFLAGS =

include ../../../../Makefile.in
